[package]
name = "euler-rust"
version = "0.1.0"
authors = ["Roger Andersen <hexjelly@hexjelly.com>"]
edition = "2018"

[lib]
name = "euler"
path = "src/lib/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
